/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Carrousel: typeof import('./src/components/Carrousel.vue')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    CartModal: typeof import('./src/components/CartModal.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LoginRegisterForm: typeof import('./src/components/LoginRegisterForm.vue')['default']
    MenuItemCard: typeof import('./src/components/MenuItemCard.vue')['default']
    NotificationToast: typeof import('./src/components/NotificationToast.vue')['default']
    RestaurantCard: typeof import('./src/components/RestaurantCard.vue')['default']
    RestaurantGrid: typeof import('./src/components/RestaurantGrid.vue')['default']
    RestaurantMenuModal: typeof import('./src/components/RestaurantMenuModal.vue')['default']
    RestaurantTypeItem: typeof import('./src/components/RestaurantTypeItem.vue')['default']
    TypeRestaurant: typeof import('./src/components/TypeRestaurant.vue')['default']
  }
}
